<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Problem-Statement" data-toc-modified-id="Problem-Statement-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Problem Statement</a></span><ul class="toc-item"><li><span><a href="#Solution" data-toc-modified-id="Solution-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Solution</a></span></li><li><span><a href="#Solution" data-toc-modified-id="Solution-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Solution</a></span></li></ul></li><li><span><a href="#Problem-Statement" data-toc-modified-id="Problem-Statement-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Problem Statement</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Question</a></span><ul class="toc-item"><li><span><a href="#Solution---Normal-for-loop" data-toc-modified-id="Solution---Normal-for-loop-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Solution - Normal for loop</a></span></li><li><span><a href="#Solution---Using-list-Comprehension" data-toc-modified-id="Solution---Using-list-Comprehension-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Solution - Using list Comprehension</a></span></li></ul></li></ul></div>

# Problem Statement
Write a function so that the columns of the output matrix are powers of the input vector.<br>
The order of the powers is determined by the increasing boolean argument. <br>
Specifically,when increasing is False,the i-th output column is the input vector raised element-wise to the power of N-i-1.<br>
**HINT:** Such a matrix with a geometric progression in each row is named for **AlexandreTheophile Vandermonde**.<br>

**Breakdown Points:**<br>
Write a function so that the columns of the output matrix are powers of the input vector.<br>
`Create a matrix that each and every columns of the output matrix should be`<br>
`The power of the input columns given`<br>

The order of the powers is determined by the increasing boolean argument.<br>
`The power can be in Increasing/Decreasing Order defined by an argument`<br>

when increasing is False,the i-th output column is the input vector raised element-wise to the power of N-i-1.<br>
`If The increasing order is False, all the elements power will be N-i-1, else`<br>
`If The increasing order is True, all the elements power will be N`<br>

What is ?<br>
`vector = Input List / Array`<br>
`N      = Number of Columns in the Matrix`<br>
`i      = Current Column index`<br><br>

**Target: To Create Matrix from given Vector**

In [34]:
vector   = [1, 2, 4, 6, 8, 10]       # Input List / Array
N        = 5                         # Number of Columns in the Matrix
Matrix_i = []
Matrix_d = []

In [35]:
for i in vector:                     # Get elements of the vector
    for j in range(N):               # Get column numbers(power) : By default power will be increasing order
        Matrix_i.append(i**j)        # Create the result

print(Matrix_i)

[1, 1, 1, 1, 1, 1, 2, 4, 8, 16, 1, 4, 16, 64, 256, 1, 6, 36, 216, 1296, 1, 8, 64, 512, 4096, 1, 10, 100, 1000, 10000]


In [36]:
for i in vector:                     # Get elements of the vector
    for j in range(N):               # Get column numbers(power) : increasing = False : power = N-i-1
        Matrix_d.append(i**(N-j-1))  # Create the result

print(Matrix_d)

[1, 1, 1, 1, 1, 16, 8, 4, 2, 1, 256, 64, 16, 4, 1, 1296, 216, 36, 6, 1, 4096, 512, 64, 8, 1, 10000, 1000, 100, 10, 1]


In [37]:
import numpy as np

arr_i = np.array(Matrix_i)            # Convert to Array
arr_d = np.array(Matrix_d)            # Convert to Array

In [38]:
arr_i.reshape(len(vector), N)         # Convert to Matrix

array([[    1,     1,     1,     1,     1],
       [    1,     2,     4,     8,    16],
       [    1,     4,    16,    64,   256],
       [    1,     6,    36,   216,  1296],
       [    1,     8,    64,   512,  4096],
       [    1,    10,   100,  1000, 10000]])

In [39]:
arr_d.reshape(len(vector), N)         # Convert to Matrix

array([[    1,     1,     1,     1,     1],
       [   16,     8,     4,     2,     1],
       [  256,    64,    16,     4,     1],
       [ 1296,   216,    36,     6,     1],
       [ 4096,   512,    64,     8,     1],
       [10000,  1000,   100,    10,     1]])

## Solution

In [49]:
import numpy as np

def Vandermonde_Mat(vector, N=None, increasing=True):
    
    # Condition for vector
    vector     = [int(i) for i in vector.split(',')]
    if len(vector) <= 1:
        print('Error : Minimum Two elements required')
    
    # Condition for N
    if N is None:
        N = len(vector)
    elif not isinstance(N, int) and not None:
        print('Error : Please provide integer value')
    
    # Condition for increasing and create Matrix
    if type(increasing) != bool:
        print('Error : Please provide Boolean value')
    elif increasing:
        print('### Power is in Increasing Order ###\n')
        return np.array([i**j for i in vector for j in range(N)]).reshape(len(vector), N)
    elif not increasing:
        print(' ### Power is in Decresing Order  ###\n')
        return np.array([i**(N-j-1) for i in vector for j in range(N)]).reshape(len(vector), N)

In [50]:
print(Vandermonde_Mat('1, 2, 4, 6, 8, 10', 5, True))   # Increasing Order

### Power is in Increasing Order ###

[[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]]


In [51]:
print(Vandermonde_Mat('1, 2, 4, 6, 8, 10', 5, False))   # Decreasing Order

 ### Power is in Decresing Order  ###

[[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]]


In [52]:
print(Vandermonde_Mat('1, 2, 4, 6, 8, 10', increasing=False))   # Without i

 ### Power is in Decresing Order  ###

[[     1      1      1      1      1      1]
 [    32     16      8      4      2      1]
 [  1024    256     64     16      4      1]
 [  7776   1296    216     36      6      1]
 [ 32768   4096    512     64      8      1]
 [100000  10000   1000    100     10      1]]


## Solution
Ref: https://numpy.org/doc/stable/reference/generated/numpy.vander.html

In [54]:
import numpy as np
from numpy import vander

x = np.array([1, 2, 3, 5])

In [55]:
vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [56]:
vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

# Problem Statement
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows<br>
The moving average sequence has n-k+1 elements as shown below.<br>
The moving averages with k=4 of a ten-value sequence (n=10) is shown below<br><br>

**Input =  10 20 30 40 50 60 70 80 90 100**<br><br>
y1 25 = (10+20+30+40)/4 <br>
y2 35 = (20+30+40+50)/4 <br>
y3 45 = (30+40+50+60)/4 <br>
y4 55 = (40+50+60+70)/4 <br>
y5 65 = (50+60+70+80)/4 <br>
y6 75 = (60+70+80+90)/4 <br>
y7 85 = (70+80+90+100)/4<br><br>

Thus, the moving average sequence has **n-k+1 = 10-4+1 = 7** values.<br>

In [1]:
sequence = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
n        = len(sequence)
k        = 4

seq_moving_avg = 10 - 4 + 1   # n-k+1

# Question

**Question:**<br>
Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

## Solution - Normal for loop

In [3]:
import numpy as np

In [4]:
def moving_average(seq, window):
    seq = [int(i) for i in seq.split(',')]
    n   = len(seq)
    k   = window
    mal = n - k + 1 # moving average length
    avg =[]
    
    # Condition for sequence
    if n < k:
        print('Error : Seq : Minimum required elements should be Greater than or Equal to Window size')
    
    # Condition for k
    if not isinstance(k, int):
        print('Error : Window : Please provide integer value')
    
    for i in range(n):
        if len(seq) >= k:
            avg.append(sum([j for j in seq[:k]])/k)
            seq.pop(0)
        else:
            return np.array(avg)

In [5]:
ma = moving_average('3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150', 3)
ma

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [6]:
ma.size

11

## Solution - Using list Comprehension

In [7]:
def moving_average(seq, window):
    seq = [int(i) for i in seq.split(',')]
    n   = len(seq)
    k   = window
    
    # moving average length
    mal = n - k + 1
    
    # Condition for sequence
    if n < k:
        print('Error : Seq : Minimum required elements should be Greater than or Equal to Window size')
    
    # Condition for k
    if not isinstance(k, int):
        print('Error : Window : Please provide integer value')
    
    return np.array([sum([j for j in seq[i:i+k]])/k for i in range(n) if i < mal])

In [8]:
ma = moving_average('3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150', 3)
ma

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [9]:
ma.size

11